#step1
#Spatial Autocorrelation null model 

#surgated MRI metrics generated by BrainSMASH
HC08_L1_sur_FA<-read.csv('E:\\Mouse2022\\ADmouse\\spot_voxels_surgate\\HC08_L1_FA_sur.csv',header = F)
HC08_M1_sur_FA<-read.csv('E:\\Mouse2022\\ADmouse\\spot_voxels_surgate\\HC08_M1_FA_sur.csv',header = F)
HC08_S1_sur_FA<-read.csv('E:\\Mouse2022\\ADmouse\\spot_voxels_surgate\\HC08_S1_FA_sur.csv',header = F)

HC08_L1_sur_sec_FA<-sections_sur(HC08_L1_sur_FA)
HC08_M1_sur_sec_FA<-sections_sur(HC08_M1_sur_FA)
HC08_S1_sur_sec_FA<-sections_sur(HC08_S1_sur_FA)

HC08_sur_sec_bind_FA<-rbind(HC08_L1_sur_sec_FA,
                            rbind(HC08_M1_sur_sec_FA,
                                  HC08_S1_sur_sec_FA))
write.csv(HC08_sur_sec_bind_FA,'E:\\Mouse2022\\ADmouse\\sur_data\\HC08_sur_sec_bind_FA.csv')


#calculate raw correlation between surgated MRI metrics and ST genes
sur_sec_bind_allgene_zero_FA<-gene_metric_spearman_zero(HC08_gene,HC08_sur_sec_bind_FA,8)
sur_sec_bind_allgene_FA<-gene_metric_spearman(HC08_gene,HC08_sur_sec_bind_FA,8)

save(sur_sec_bind_allgene_zero_FA,sur_sec_bind_allgene_FA,file = 'E:\\Mouse2022\\ADmouse\\result\\r_sur_bind100_FA_HC.Rdata')
load('E:\\Mouse2022\\ADmouse\\result\\r_sur_bind100_FA_HC.Rdata')


sections_sur<-function(table){
  c<-data.frame()
  for (i in 1:1000) {
    a<-strsplit(table$V1[i],split = ' ')
    b<-as.data.frame(a)
    if(i==1){
      c<-b
    }else{
      c<-cbind(c,b)
    }
    
  }
  colnames(c)<-1:1000
  return(c)
}